-- Snowcore Anomaly Detection DDL
-- Database and Schema Setup

-- Main database
CREATE DATABASE IF NOT EXISTS SNOWCORE_PDM;
USE DATABASE SNOWCORE_PDM;

-- Schema layers
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ATOMIC;
CREATE SCHEMA IF NOT EXISTS PDM;
CREATE SCHEMA IF NOT EXISTS DATA_MART;
CREATE SCHEMA IF NOT EXISTS CONFIG;
CREATE SCHEMA IF NOT EXISTS AUDIT;

-- ============================================================================
-- RAW LAYER: Landing zone for Sparkplug B JSON payloads
-- ============================================================================

CREATE OR REPLACE TABLE RAW.IOT_STREAMING (
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM RAW.IOT_STREAMING_STREAM 
ON TABLE RAW.IOT_STREAMING;

-- ============================================================================
-- ATOMIC LAYER: Normalized, time-aligned sensor readings
-- ============================================================================

CREATE OR REPLACE DYNAMIC TABLE ATOMIC.ASSET_SENSORS
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    RECORD_CONTENT:timestamp::TIMESTAMP_NTZ AS EVENT_TIMESTAMP,
    SPLIT_PART(RECORD_METADATA:topic::STRING, '/', 4) AS EDGE_NODE,
    SPLIT_PART(RECORD_METADATA:topic::STRING, '/', 5) AS ASSET_ID,
    m.value:name::STRING AS METRIC_NAME,
    m.value:value::FLOAT AS METRIC_VALUE,
    m.value:dataType::STRING AS DATA_TYPE
FROM RAW.IOT_STREAMING,
LATERAL FLATTEN(input => RECORD_CONTENT:metrics) m;

CREATE OR REPLACE DYNAMIC TABLE ATOMIC.ASSET_SENSORS_WIDE
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EVENT_TIMESTAMP,
    ASSET_ID,
    MAX(CASE WHEN METRIC_NAME = 'Temperature' THEN METRIC_VALUE END) AS TEMPERATURE_C,
    MAX(CASE WHEN METRIC_NAME = 'Pressure' THEN METRIC_VALUE END) AS PRESSURE_PSI,
    MAX(CASE WHEN METRIC_NAME = 'VacuumLevel' THEN METRIC_VALUE END) AS VACUUM_MBAR,
    MAX(CASE WHEN METRIC_NAME = 'Humidity' THEN METRIC_VALUE END) AS HUMIDITY_PCT,
    MAX(CASE WHEN METRIC_NAME = 'Vibration' THEN METRIC_VALUE END) AS VIBRATION_G,
    MAX(CASE WHEN METRIC_NAME = 'TensionForce' THEN METRIC_VALUE END) AS TENSION_FORCE_N,
    MAX(CASE WHEN METRIC_NAME = 'FeedRate' THEN METRIC_VALUE END) AS FEED_RATE_MPS,
    MAX(CASE WHEN METRIC_NAME = 'SpindleSpeed' THEN METRIC_VALUE END) AS SPINDLE_SPEED_RPM,
    MAX(CASE WHEN METRIC_NAME = 'CoolantTemp' THEN METRIC_VALUE END) AS COOLANT_TEMP_C
FROM ATOMIC.ASSET_SENSORS
GROUP BY EVENT_TIMESTAMP, ASSET_ID;

CREATE OR REPLACE TABLE ATOMIC.MAINTENANCE_LOGS (
    LOG_ID STRING DEFAULT UUID_STRING(),
    ASSET_ID STRING,
    TIMESTAMP TIMESTAMP_NTZ,
    FAILURE_REASON STRING,
    DOWNTIME_MINUTES INTEGER,
    TECHNICIAN_ID STRING,
    WORK_ORDER_ID STRING,
    RESOLUTION_NOTES STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ATOMIC.PRODUCTION_BATCHES (
    BATCH_ID STRING,
    PRODUCT_LINE STRING DEFAULT 'AVALANCHE_X1',
    LAYUP_START TIMESTAMP_NTZ,
    LAYUP_END TIMESTAMP_NTZ,
    CURE_START TIMESTAMP_NTZ,
    CURE_END TIMESTAMP_NTZ,
    TRIM_START TIMESTAMP_NTZ,
    TRIM_END TIMESTAMP_NTZ,
    QC_TIMESTAMP TIMESTAMP_NTZ,
    QC_RESULT STRING,
    SCRAP_FLAG BOOLEAN DEFAULT FALSE,
    DELAMINATION_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- PDM LAYER: Predictive Maintenance Analytics
-- ============================================================================

CREATE OR REPLACE TABLE PDM.FEATURE_STORE (
    FEATURE_ID STRING DEFAULT UUID_STRING(),
    ASSET_ID STRING,
    WINDOW_START TIMESTAMP_NTZ,
    WINDOW_END TIMESTAMP_NTZ,
    TEMP_MEAN FLOAT,
    TEMP_STD FLOAT,
    TEMP_MIN FLOAT,
    TEMP_MAX FLOAT,
    PRESSURE_MEAN FLOAT,
    PRESSURE_STD FLOAT,
    VIBRATION_MEAN FLOAT,
    VIBRATION_MAX FLOAT,
    HUMIDITY_MEAN FLOAT,
    HUMIDITY_MAX FLOAT,
    DRIFT_SCORE FLOAT,
    HEALTH_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.ANOMALY_EVENTS (
    EVENT_ID STRING DEFAULT UUID_STRING(),
    ASSET_ID STRING,
    TIMESTAMP TIMESTAMP_NTZ,
    ANOMALY_TYPE STRING,
    ANOMALY_SCORE FLOAT,
    SEVERITY STRING,
    ROOT_CAUSE STRING,
    SUGGESTED_FIX STRING,
    RESOLVED BOOLEAN DEFAULT FALSE,
    RESOLUTION_TIMESTAMP TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.CURE_RESULTS (
    RESULT_ID STRING DEFAULT UUID_STRING(),
    BATCH_ID STRING,
    AUTOCLAVE_ID STRING,
    CURE_TIMESTAMP TIMESTAMP_NTZ,
    LAYUP_HUMIDITY_AVG FLOAT,
    LAYUP_HUMIDITY_PEAK FLOAT,
    SCRAP_FLAG BOOLEAN,
    DELAMINATION_SCORE FLOAT,
    FAILURE_MODE STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.KNOWLEDGE_BASE (
    DOC_ID STRING DEFAULT UUID_STRING(),
    DOC_TYPE STRING,
    ASSET_MODEL STRING,
    COMPONENT_SECTION STRING,
    ERROR_CODE STRING,
    TITLE STRING,
    CONTENT STRING,
    SOURCE_FILE STRING,
    CHUNK_INDEX INTEGER,
    EMBEDDING VECTOR(FLOAT, 768),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DATA_MART LAYER: Aggregated metrics for dashboards
-- ============================================================================

CREATE OR REPLACE TABLE DATA_MART.FINANCIAL_SUMMARY (
    SUMMARY_ID STRING DEFAULT UUID_STRING(),
    MONTH DATE,
    DOWNTIME_HOURS FLOAT,
    DOWNTIME_COST_USD FLOAT,
    SCRAP_COUNT INTEGER,
    SCRAP_COST_USD FLOAT,
    CORRECTIVE_MAINT_HRS FLOAT,
    PREVENTIVE_MAINT_HRS FLOAT,
    LABOR_VARIANCE_USD FLOAT,
    INVENTORY_VALUE_USD FLOAT,
    STOCKOUT_EVENTS INTEGER,
    OEE_PCT FLOAT,
    SCENARIO STRING DEFAULT 'BEFORE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DATA_MART.ASSET_STATUS (
    STATUS_ID STRING DEFAULT UUID_STRING(),
    ASSET_ID STRING,
    ASSET_NAME STRING,
    ASSET_TYPE STRING,
    LINE_ID STRING,
    STATUS STRING,
    HEALTH_SCORE FLOAT,
    LAST_ANOMALY_TIME TIMESTAMP_NTZ,
    LAST_MAINTENANCE_TIME TIMESTAMP_NTZ,
    POSITION_X INTEGER,
    POSITION_Y INTEGER,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DATA_MART.KPI_METRICS (
    METRIC_ID STRING DEFAULT UUID_STRING(),
    METRIC_DATE DATE,
    METRIC_NAME STRING,
    METRIC_VALUE FLOAT,
    METRIC_UNIT STRING,
    BEFORE_VALUE FLOAT,
    AFTER_VALUE FLOAT,
    IMPROVEMENT_PCT FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- CONFIG LAYER: Application configuration
-- ============================================================================

CREATE OR REPLACE TABLE CONFIG.AGENT_SETTINGS (
    SETTING_ID STRING DEFAULT UUID_STRING(),
    USER_ID STRING,
    ROLE STRING,
    AUTONOMY_LEVEL INTEGER DEFAULT 2,
    AUTO_CREATE_WO BOOLEAN DEFAULT FALSE,
    AUTO_NOTIFY BOOLEAN DEFAULT FALSE,
    NOTIFICATION_CHANNELS ARRAY,
    TRUSTED_PLAYBOOKS ARRAY,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CONFIG.AGENT_SETTINGS (USER_ID, ROLE, AUTONOMY_LEVEL, AUTO_CREATE_WO)
VALUES 
    ('default_operator', 'OPERATOR', 2, FALSE),
    ('default_lead', 'MAINTENANCE_LEAD', 2, TRUE),
    ('default_manager', 'PLANT_MANAGER', 1, FALSE);

CREATE OR REPLACE TABLE CONFIG.ASSET_GRAPH (
    EDGE_ID STRING DEFAULT UUID_STRING(),
    SOURCE_ASSET STRING,
    TARGET_ASSET STRING,
    EDGE_TYPE STRING,
    WEIGHT FLOAT DEFAULT 1.0,
    LAG_HOURS FLOAT DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CONFIG.ASSET_GRAPH (SOURCE_ASSET, TARGET_ASSET, EDGE_TYPE, WEIGHT, LAG_HOURS)
VALUES
    ('LAYUP_ROOM', 'LAYUP_BOT_01', 'ENV_INFLUENCE', 0.8, 0),
    ('LAYUP_ROOM', 'LAYUP_BOT_02', 'ENV_INFLUENCE', 0.8, 0),
    ('LAYUP_BOT_01', 'AUTOCLAVE_01', 'MATERIAL_FLOW', 1.0, 2),
    ('LAYUP_BOT_02', 'AUTOCLAVE_02', 'MATERIAL_FLOW', 1.0, 2),
    ('AUTOCLAVE_01', 'CNC_MILL_01', 'MATERIAL_FLOW', 1.0, 4),
    ('AUTOCLAVE_02', 'CNC_MILL_02', 'MATERIAL_FLOW', 1.0, 4),
    ('CNC_MILL_01', 'QC_STATION_01', 'MATERIAL_FLOW', 1.0, 1),
    ('CNC_MILL_02', 'QC_STATION_02', 'MATERIAL_FLOW', 1.0, 1);

-- ============================================================================
-- AUDIT LAYER: Action logging
-- ============================================================================

CREATE OR REPLACE TABLE AUDIT.AGENT_ACTIONS (
    ACTION_ID STRING DEFAULT UUID_STRING(),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_ID STRING,
    AUTONOMY_LEVEL INTEGER,
    ACTION_TYPE STRING,
    ACTION_DETAIL VARIANT,
    ANOMALY_EVENT_ID STRING,
    APPROVAL_STATUS STRING,
    RESULT VARIANT
);

-- ============================================================================
-- VIEWS: Analytical views for dashboards
-- ============================================================================

CREATE OR REPLACE VIEW DATA_MART.V_HUMIDITY_SCRAP_CORRELATION AS
WITH layup_humidity AS (
    SELECT 
        BATCH_ID,
        AVG(LAYUP_HUMIDITY_AVG) AS avg_humidity,
        MAX(LAYUP_HUMIDITY_PEAK) AS peak_humidity
    FROM PDM.CURE_RESULTS
    GROUP BY BATCH_ID
),
cure_outcomes AS (
    SELECT 
        BATCH_ID,
        SCRAP_FLAG,
        DELAMINATION_SCORE
    FROM PDM.CURE_RESULTS
)
SELECT 
    CASE WHEN lh.peak_humidity > 65 THEN 'HIGH_HUMIDITY' ELSE 'NORMAL' END AS humidity_class,
    COUNT(*) AS batches,
    SUM(CASE WHEN co.SCRAP_FLAG THEN 1 ELSE 0 END) AS scrap_count,
    ROUND(SUM(CASE WHEN co.SCRAP_FLAG THEN 1 ELSE 0 END) / COUNT(*) * 100, 1) AS scrap_rate_pct
FROM layup_humidity lh
JOIN cure_outcomes co USING (BATCH_ID)
GROUP BY 1;

CREATE OR REPLACE VIEW DATA_MART.V_TOTAL_VALUE_CREATED AS
SELECT
    SUM(CASE WHEN SCENARIO = 'BEFORE' THEN DOWNTIME_COST_USD ELSE 0 END) -
    SUM(CASE WHEN SCENARIO = 'AFTER' THEN DOWNTIME_COST_USD ELSE 0 END) AS downtime_savings,
    SUM(CASE WHEN SCENARIO = 'BEFORE' THEN SCRAP_COST_USD ELSE 0 END) -
    SUM(CASE WHEN SCENARIO = 'AFTER' THEN SCRAP_COST_USD ELSE 0 END) AS scrap_savings,
    SUM(CASE WHEN SCENARIO = 'BEFORE' THEN LABOR_VARIANCE_USD ELSE 0 END) -
    SUM(CASE WHEN SCENARIO = 'AFTER' THEN LABOR_VARIANCE_USD ELSE 0 END) AS labor_savings,
    (downtime_savings + scrap_savings + labor_savings) * 12 AS annual_value_usd
FROM DATA_MART.FINANCIAL_SUMMARY
WHERE MONTH >= DATEADD('month', -1, CURRENT_DATE());

-- ============================================================================
-- PDM LAYER: Model Outputs (Notebook Results)
-- ============================================================================

CREATE OR REPLACE TABLE PDM.MODEL_DIAGNOSTICS (
    DIAGNOSTIC_ID STRING DEFAULT UUID_STRING(),
    MODEL_NAME STRING,
    MODEL_VERSION STRING,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME STRING,
    METRIC_VALUE FLOAT,
    THRESHOLD_VALUE FLOAT,
    STATUS STRING,
    DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.GNN_PROPAGATION_SCORES (
    SCORE_ID STRING DEFAULT UUID_STRING(),
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_ASSET STRING,
    TARGET_ASSET STRING,
    PROPAGATION_SCORE FLOAT,
    PROPAGATION_TYPE STRING,
    EDGE_TYPE STRING,
    HOP_DISTANCE INTEGER,
    CONFIDENCE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.MODEL_METRICS (
    METRIC_ID STRING DEFAULT UUID_STRING(),
    MODEL_NAME STRING,
    MODEL_VERSION STRING,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME STRING,
    METRIC_VALUE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PDM.MAINTENANCE_DECISIONS_LIVE (
    DECISION_ID STRING DEFAULT UUID_STRING(),
    ASSET_ID STRING,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECOMMENDATION STRING,
    CONFIDENCE FLOAT,
    NET_BENEFIT FLOAT,
    REASONING STRING,
    MODEL_VERSION STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
