-- Cortex Search Service Setup for Knowledge Base

USE DATABASE SNOWCORE_PDM;
USE SCHEMA PDM;

CREATE OR REPLACE CORTEX SEARCH SERVICE KNOWLEDGE_BASE_SEARCH
ON CONTENT
ATTRIBUTES DOC_TYPE, ASSET_MODEL, COMPONENT_SECTION, ERROR_CODE, TITLE, SOURCE_FILE
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 hour'
AS (
    SELECT
        DOC_ID,
        DOC_TYPE,
        ASSET_MODEL,
        COMPONENT_SECTION,
        ERROR_CODE,
        TITLE,
        CONTENT,
        SOURCE_FILE,
        CHUNK_INDEX
    FROM PDM.KNOWLEDGE_BASE
);

GRANT USAGE ON CORTEX SEARCH SERVICE KNOWLEDGE_BASE_SEARCH TO ROLE PUBLIC;
