-- Load data from staged CSV files

USE DATABASE SNOWCORE_PDM;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');

COPY INTO ATOMIC.PRODUCTION_BATCHES (BATCH_ID, PRODUCT_LINE, LAYUP_START, LAYUP_END, CURE_START, CURE_END, TRIM_START, TRIM_END, QC_TIMESTAMP, QC_RESULT, SCRAP_FLAG, DELAMINATION_SCORE)
FROM @RAW.DATA_STAGE/production_batches.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO PDM.CURE_RESULTS (BATCH_ID, AUTOCLAVE_ID, CURE_TIMESTAMP, LAYUP_HUMIDITY_AVG, LAYUP_HUMIDITY_PEAK, SCRAP_FLAG, DELAMINATION_SCORE, FAILURE_MODE)
FROM @RAW.DATA_STAGE/cure_results.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO ATOMIC.MAINTENANCE_LOGS (LOG_ID, ASSET_ID, TIMESTAMP, FAILURE_REASON, DOWNTIME_MINUTES, TECHNICIAN_ID, WORK_ORDER_ID, RESOLUTION_NOTES)
FROM @RAW.DATA_STAGE/maintenance_logs.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO PDM.ANOMALY_EVENTS (EVENT_ID, ASSET_ID, TIMESTAMP, ANOMALY_TYPE, ANOMALY_SCORE, SEVERITY, ROOT_CAUSE, SUGGESTED_FIX, RESOLVED)
FROM @RAW.DATA_STAGE/anomaly_events.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO DATA_MART.FINANCIAL_SUMMARY (MONTH, DOWNTIME_HOURS, DOWNTIME_COST_USD, SCRAP_COUNT, SCRAP_COST_USD, CORRECTIVE_MAINT_HRS, PREVENTIVE_MAINT_HRS, LABOR_VARIANCE_USD, INVENTORY_VALUE_USD, STOCKOUT_EVENTS, OEE_PCT, SCENARIO)
FROM @RAW.DATA_STAGE/financial_summary.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO DATA_MART.ASSET_STATUS (ASSET_ID, ASSET_NAME, ASSET_TYPE, LINE_ID, STATUS, HEALTH_SCORE, LAST_ANOMALY_TIME, LAST_MAINTENANCE_TIME, POSITION_X, POSITION_Y)
FROM @RAW.DATA_STAGE/asset_status.csv
FILE_FORMAT = RAW.CSV_FORMAT;

COPY INTO PDM.KNOWLEDGE_BASE (DOC_TYPE, ASSET_MODEL, COMPONENT_SECTION, ERROR_CODE, TITLE, CONTENT, SOURCE_FILE, CHUNK_INDEX)
FROM @RAW.DATA_STAGE/knowledge_base.csv
FILE_FORMAT = RAW.CSV_FORMAT;
